global:
    title: Selene Software
    subtitle: Custom Web Software Development

index:

about:
    description: "Selene software is a custom web development firm in Detroit, specializing in PHP, JavaScript, and CSS."

